inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*.rb'

Rails:
  Enabled: true

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false
