inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*.rb'

Rails:
  Enabled: true

# Layout
Layout/LineLength:
  Enabled: false

# Style
# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# classの行頭にクラスに関するコメントを書かなくても良い
Style/Documentation:
  Enabled: false
